-- ============================================================================
-- NEWSLETTER CORE SCHEMA
-- Lists, segments, subscribers, tags, templates, campaigns, recipients,
-- events, links, conversions, suppressions, providers and settings.
--
-- Conventions used across this module:
--   * uuid primary keys generated by gen_random_uuid()
--   * timestamptz everywhere, never timestamp
--   * soft delete via deleted_at ONLY where LGPD/audit requires retention
--   * every table in the exposed `public` schema gets RLS enabled immediately
--     (policies are attached in the newsletter_rbac_audit migration)
-- ============================================================================

create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";

-- ----------------------------------------------------------------------------
-- Enum types (guarded so the migration is safe to replay)
-- ----------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_type where typname = 'newsletter_subscriber_status') then
    create type public.newsletter_subscriber_status as enum
      ('pending', 'active', 'unsubscribed', 'bounced', 'complained', 'cleaned');
  end if;

  if not exists (select 1 from pg_type where typname = 'newsletter_consent_source') then
    create type public.newsletter_consent_source as enum
      ('website_form', 'landing_page', 'admin_import', 'api', 'event', 'referral', 'partner', 'other');
  end if;

  if not exists (select 1 from pg_type where typname = 'newsletter_campaign_status') then
    create type public.newsletter_campaign_status as enum
      ('draft', 'scheduled', 'queued', 'sending', 'paused', 'sent', 'canceled', 'failed');
  end if;

  if not exists (select 1 from pg_type where typname = 'newsletter_recipient_status') then
    create type public.newsletter_recipient_status as enum
      ('queued', 'sending', 'sent', 'delivered', 'opened', 'clicked', 'bounced', 'complained', 'unsubscribed', 'failed', 'skipped');
  end if;

  if not exists (select 1 from pg_type where typname = 'newsletter_event_type') then
    create type public.newsletter_event_type as enum
      ('queued', 'sent', 'delivered', 'open', 'click', 'bounce', 'complaint', 'unsubscribe', 'resubscribe', 'deferred', 'blocked', 'rejected', 'failed');
  end if;

  if not exists (select 1 from pg_type where typname = 'newsletter_provider_kind') then
    create type public.newsletter_provider_kind as enum
      ('resend', 'smtp', 'sendgrid', 'mailgun', 'ses', 'postmark');
  end if;

  if not exists (select 1 from pg_type where typname = 'newsletter_bounce_type') then
    create type public.newsletter_bounce_type as enum ('hard', 'soft', 'unknown');
  end if;

  if not exists (select 1 from pg_type where typname = 'newsletter_ab_variant') then
    create type public.newsletter_ab_variant as enum ('a', 'b');
  end if;
end
$$;

-- ----------------------------------------------------------------------------
-- Shared trigger helper
-- ----------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ----------------------------------------------------------------------------
-- 1. Lists
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_lists (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  slug           text not null,
  description    text,
  is_default     boolean not null default false,
  double_opt_in  boolean not null default true,
  created_by     uuid references auth.users (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz,
  constraint newsletter_lists_name_not_blank check (length(btrim(name)) > 0),
  constraint newsletter_lists_slug_format check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

comment on table public.newsletter_lists is 'Named audiences (e.g. "Informativo Tributário") that campaigns are sent to.';

create unique index if not exists newsletter_lists_slug_key
  on public.newsletter_lists (slug) where deleted_at is null;

create unique index if not exists newsletter_lists_single_default_idx
  on public.newsletter_lists (is_default) where is_default and deleted_at is null;

drop trigger if exists newsletter_lists_set_updated_at on public.newsletter_lists;
create trigger newsletter_lists_set_updated_at
  before update on public.newsletter_lists
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 2. Tags
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_tags (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  color       text not null default '#D4AF37',
  description text,
  created_by  uuid references auth.users (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint newsletter_tags_name_not_blank check (length(btrim(name)) > 0)
);

create unique index if not exists newsletter_tags_name_key
  on public.newsletter_tags (lower(btrim(name)));

drop trigger if exists newsletter_tags_set_updated_at on public.newsletter_tags;
create trigger newsletter_tags_set_updated_at
  before update on public.newsletter_tags
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 3. Subscribers (additive migration on top of the legacy table)
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_subscribers (
  id               uuid primary key default gen_random_uuid(),
  email            text not null,
  preference_area  text not null default 'Todas as Matérias',
  created_at       timestamptz not null default now()
);

alter table public.newsletter_subscribers
  add column if not exists name                     text,
  add column if not exists status                   public.newsletter_subscriber_status not null default 'pending',
  add column if not exists phone                    text,
  add column if not exists company                  text,
  add column if not exists job_title                text,
  add column if not exists locale                   text not null default 'pt-BR',
  add column if not exists timezone                 text not null default 'America/Sao_Paulo',
  add column if not exists source                   public.newsletter_consent_source not null default 'other',
  add column if not exists source_detail            text,
  add column if not exists consent_given_at         timestamptz,
  add column if not exists consent_ip               inet,
  add column if not exists consent_user_agent       text,
  add column if not exists consent_text             text,
  add column if not exists confirmed_at             timestamptz,
  add column if not exists confirmation_token       uuid,
  add column if not exists confirmation_sent_at     timestamptz,
  add column if not exists unsubscribed_at          timestamptz,
  add column if not exists unsubscribe_reason       text,
  add column if not exists unsubscribe_token        uuid not null default gen_random_uuid(),
  add column if not exists bounce_count             integer not null default 0,
  add column if not exists last_bounce_at           timestamptz,
  add column if not exists last_event_at            timestamptz,
  add column if not exists engagement_score         numeric(5, 2) not null default 0,
  add column if not exists custom_fields            jsonb not null default '{}'::jsonb,
  add column if not exists notes                    text,
  add column if not exists created_by               uuid references auth.users (id) on delete set null,
  add column if not exists updated_at               timestamptz not null default now(),
  add column if not exists anonymized_at            timestamptz,
  add column if not exists deleted_at               timestamptz;

-- Legacy rows were created through the public form without consent metadata.
update public.newsletter_subscribers
   set status = 'active',
       confirmed_at = coalesce(confirmed_at, created_at),
       consent_given_at = coalesce(consent_given_at, created_at)
 where confirmed_at is null
   and status = 'pending';

create unique index if not exists newsletter_subscribers_email_key
  on public.newsletter_subscribers (lower(btrim(email)));

create index if not exists newsletter_subscribers_status_created_idx
  on public.newsletter_subscribers (status, created_at desc)
  where deleted_at is null;

create index if not exists newsletter_subscribers_source_idx
  on public.newsletter_subscribers (source)
  where deleted_at is null;

create index if not exists newsletter_subscribers_email_trgm_idx
  on public.newsletter_subscribers using gin (email gin_trgm_ops);

create index if not exists newsletter_subscribers_name_trgm_idx
  on public.newsletter_subscribers using gin (name gin_trgm_ops);

create index if not exists newsletter_subscribers_custom_fields_idx
  on public.newsletter_subscribers using gin (custom_fields jsonb_path_ops);

drop trigger if exists newsletter_subscribers_set_updated_at on public.newsletter_subscribers;
create trigger newsletter_subscribers_set_updated_at
  before update on public.newsletter_subscribers
  for each row execute function public.set_updated_at();

-- Always persist a canonical, lower-cased, trimmed address.
create or replace function public.newsletter_normalize_subscriber()
returns trigger
language plpgsql
as $$
begin
  new.email := lower(btrim(new.email));
  if new.status = 'active' and new.confirmed_at is null then
    new.confirmed_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists newsletter_subscribers_normalize on public.newsletter_subscribers;
create trigger newsletter_subscribers_normalize
  before insert or update of email on public.newsletter_subscribers
  for each row execute function public.newsletter_normalize_subscriber();

-- ----------------------------------------------------------------------------
-- 4. List membership
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_list_members (
  list_id       uuid not null references public.newsletter_lists (id) on delete cascade,
  subscriber_id uuid not null references public.newsletter_subscribers (id) on delete cascade,
  status        public.newsletter_subscriber_status not null default 'active',
  joined_at     timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  primary key (list_id, subscriber_id)
);

create index if not exists newsletter_list_members_subscriber_idx
  on public.newsletter_list_members (subscriber_id);

drop trigger if exists newsletter_list_members_set_updated_at on public.newsletter_list_members;
create trigger newsletter_list_members_set_updated_at
  before update on public.newsletter_list_members
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 5. Subscriber <-> tag join table
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_subscriber_tags (
  subscriber_id uuid not null references public.newsletter_subscribers (id) on delete cascade,
  tag_id        uuid not null references public.newsletter_tags (id) on delete cascade,
  tagged_at     timestamptz not null default now(),
  primary key (subscriber_id, tag_id)
);

create index if not exists newsletter_subscriber_tags_tag_idx
  on public.newsletter_subscriber_tags (tag_id);

-- ----------------------------------------------------------------------------
-- 6. Segments
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_segments (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  description  text,
  rules        jsonb not null default '{"match":"all","conditions":[]}'::jsonb,
  is_dynamic   boolean not null default true,
  cached_count integer not null default 0,
  cached_at    timestamptz,
  created_by   uuid references auth.users (id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz,
  constraint newsletter_segments_name_not_blank check (length(btrim(name)) > 0),
  constraint newsletter_segments_rules_is_object check (jsonb_typeof(rules) = 'object')
);

create unique index if not exists newsletter_segments_name_key
  on public.newsletter_segments (lower(btrim(name))) where deleted_at is null;

drop trigger if exists newsletter_segments_set_updated_at on public.newsletter_segments;
create trigger newsletter_segments_set_updated_at
  before update on public.newsletter_segments
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 7. Templates
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_templates (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  description   text,
  category      text not null default 'geral',
  subject       text not null default '',
  preview_text  text,
  blocks        jsonb not null default '[]'::jsonb,
  design        jsonb not null default '{}'::jsonb,
  html          text,
  thumbnail_url text,
  is_archived   boolean not null default false,
  version       integer not null default 1,
  created_by    uuid references auth.users (id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  constraint newsletter_templates_name_not_blank check (length(btrim(name)) > 0),
  constraint newsletter_templates_blocks_is_array check (jsonb_typeof(blocks) = 'array')
);

create index if not exists newsletter_templates_category_idx
  on public.newsletter_templates (category, updated_at desc)
  where deleted_at is null and not is_archived;

drop trigger if exists newsletter_templates_set_updated_at on public.newsletter_templates;
create trigger newsletter_templates_set_updated_at
  before update on public.newsletter_templates
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 8. Campaigns
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_campaigns (
  id                  uuid primary key default gen_random_uuid(),
  name                text not null,
  subject             text not null default '',
  preview_text        text,
  from_name           text,
  from_email          text,
  reply_to            text,
  list_id             uuid references public.newsletter_lists (id) on delete set null,
  segment_id          uuid references public.newsletter_segments (id) on delete set null,
  template_id         uuid references public.newsletter_templates (id) on delete set null,
  blocks              jsonb not null default '[]'::jsonb,
  design              jsonb not null default '{}'::jsonb,
  html                text,
  status              public.newsletter_campaign_status not null default 'draft',
  scheduled_at        timestamptz,
  scheduled_timezone  text not null default 'America/Sao_Paulo',
  started_at          timestamptz,
  paused_at           timestamptz,
  completed_at        timestamptz,
  canceled_at         timestamptz,
  last_error          text,
  total_recipients    integer not null default 0,
  sent_count          integer not null default 0,
  delivered_count     integer not null default 0,
  open_count          integer not null default 0,
  unique_open_count   integer not null default 0,
  click_count         integer not null default 0,
  unique_click_count  integer not null default 0,
  bounce_count        integer not null default 0,
  complaint_count     integer not null default 0,
  unsubscribe_count   integer not null default 0,
  revenue_cents       bigint not null default 0,
  ab_test_enabled     boolean not null default false,
  ab_config           jsonb not null default '{}'::jsonb,
  ab_winner_variant   public.newsletter_ab_variant,
  ab_decided_at       timestamptz,
  version             integer not null default 1,
  duplicated_from     uuid references public.newsletter_campaigns (id) on delete set null,
  created_by          uuid references auth.users (id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  deleted_at          timestamptz,
  constraint newsletter_campaigns_name_not_blank check (length(btrim(name)) > 0),
  constraint newsletter_campaigns_blocks_is_array check (jsonb_typeof(blocks) = 'array'),
  constraint newsletter_campaigns_scheduled_has_date
    check (status <> 'scheduled' or scheduled_at is not null)
);

create index if not exists newsletter_campaigns_status_schedule_idx
  on public.newsletter_campaigns (status, scheduled_at)
  where deleted_at is null;

create index if not exists newsletter_campaigns_created_idx
  on public.newsletter_campaigns (created_at desc)
  where deleted_at is null;

drop trigger if exists newsletter_campaigns_set_updated_at on public.newsletter_campaigns;
create trigger newsletter_campaigns_set_updated_at
  before update on public.newsletter_campaigns
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 9. Campaign versioning (immutable snapshots)
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_campaign_versions (
  id          uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.newsletter_campaigns (id) on delete cascade,
  version     integer not null,
  snapshot    jsonb not null,
  change_note text,
  created_by  uuid references auth.users (id) on delete set null,
  created_at  timestamptz not null default now(),
  constraint newsletter_campaign_versions_unique unique (campaign_id, version)
);

create index if not exists newsletter_campaign_versions_campaign_idx
  on public.newsletter_campaign_versions (campaign_id, version desc);

-- ----------------------------------------------------------------------------
-- 10. Sending providers
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_providers (
  id                  uuid primary key default gen_random_uuid(),
  name                text not null,
  kind                public.newsletter_provider_kind not null,
  is_active           boolean not null default false,
  is_default          boolean not null default false,
  from_name           text,
  from_email          text,
  reply_to            text,
  -- Non-secret transport settings only (region, host, port, domain).
  config              jsonb not null default '{}'::jsonb,
  -- Name of the Edge Function secret / Vault entry holding the API key.
  -- Secrets are NEVER stored in this table.
  secret_ref          text,
  webhook_secret_ref  text,
  daily_limit         integer,
  hourly_limit        integer,
  per_second_limit    integer not null default 10,
  priority            integer not null default 100,
  last_used_at        timestamptz,
  created_by          uuid references auth.users (id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint newsletter_providers_name_not_blank check (length(btrim(name)) > 0),
  constraint newsletter_providers_limits_positive
    check ((daily_limit is null or daily_limit > 0)
       and (hourly_limit is null or hourly_limit > 0)
       and per_second_limit > 0),
  constraint newsletter_providers_config_is_object check (jsonb_typeof(config) = 'object')
);

create unique index if not exists newsletter_providers_single_default_idx
  on public.newsletter_providers (is_default) where is_default;

drop trigger if exists newsletter_providers_set_updated_at on public.newsletter_providers;
create trigger newsletter_providers_set_updated_at
  before update on public.newsletter_providers
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 11. Recipients (one row per campaign x subscriber)
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_campaign_recipients (
  id                  uuid primary key default gen_random_uuid(),
  campaign_id         uuid not null references public.newsletter_campaigns (id) on delete cascade,
  subscriber_id       uuid references public.newsletter_subscribers (id) on delete set null,
  email               text not null,
  variant             public.newsletter_ab_variant,
  status              public.newsletter_recipient_status not null default 'queued',
  provider_id         uuid references public.newsletter_providers (id) on delete set null,
  provider_message_id text,
  attempts            integer not null default 0,
  max_attempts        integer not null default 3,
  last_error          text,
  next_attempt_at     timestamptz,
  queued_at           timestamptz not null default now(),
  sent_at             timestamptz,
  delivered_at        timestamptz,
  opened_at           timestamptz,
  first_clicked_at    timestamptz,
  bounced_at          timestamptz,
  bounce_type         public.newsletter_bounce_type,
  complained_at       timestamptz,
  unsubscribed_at     timestamptz,
  open_count          integer not null default 0,
  click_count         integer not null default 0,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint newsletter_recipients_attempts_valid
    check (attempts >= 0 and max_attempts > 0)
);

create unique index if not exists newsletter_recipients_campaign_subscriber_key
  on public.newsletter_campaign_recipients (campaign_id, subscriber_id);

create index if not exists newsletter_recipients_campaign_status_idx
  on public.newsletter_campaign_recipients (campaign_id, status);

create index if not exists newsletter_recipients_pending_idx
  on public.newsletter_campaign_recipients (next_attempt_at)
  where status = 'queued';

create unique index if not exists newsletter_recipients_provider_message_key
  on public.newsletter_campaign_recipients (provider_id, provider_message_id)
  where provider_message_id is not null;

drop trigger if exists newsletter_recipients_set_updated_at on public.newsletter_campaign_recipients;
create trigger newsletter_recipients_set_updated_at
  before update on public.newsletter_campaign_recipients
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 12. Links (per campaign, used for click tracking + validation)
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_links (
  id          uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.newsletter_campaigns (id) on delete cascade,
  url         text not null,
  label       text,
  tag         text,
  is_tracked  boolean not null default true,
  click_count integer not null default 0,
  last_status integer,
  last_checked_at timestamptz,
  created_at  timestamptz not null default now(),
  constraint newsletter_links_unique unique (campaign_id, url)
);

create index if not exists newsletter_links_campaign_idx
  on public.newsletter_links (campaign_id);

-- ----------------------------------------------------------------------------
-- 13. Events (append-only log of every delivery interaction)
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_events (
  id                bigserial primary key,
  campaign_id       uuid references public.newsletter_campaigns (id) on delete cascade,
  recipient_id      uuid references public.newsletter_campaign_recipients (id) on delete cascade,
  subscriber_id     uuid references public.newsletter_subscribers (id) on delete set null,
  provider_id       uuid references public.newsletter_providers (id) on delete set null,
  link_id           uuid references public.newsletter_links (id) on delete set null,
  event_type        public.newsletter_event_type not null,
  url               text,
  user_agent        text,
  ip                inet,
  country           text,
  provider_event_id text,
  bounce_type       public.newsletter_bounce_type,
  reason            text,
  occurred_at       timestamptz not null default now(),
  metadata          jsonb not null default '{}'::jsonb,
  created_at        timestamptz not null default now()
);

create unique index if not exists newsletter_events_provider_event_key
  on public.newsletter_events (provider_id, provider_event_id)
  where provider_event_id is not null;

create index if not exists newsletter_events_campaign_type_idx
  on public.newsletter_events (campaign_id, event_type, occurred_at desc);

create index if not exists newsletter_events_subscriber_idx
  on public.newsletter_events (subscriber_id, occurred_at desc);

create index if not exists newsletter_events_occurred_idx
  on public.newsletter_events (occurred_at desc);

-- ----------------------------------------------------------------------------
-- 14. Suppression list (bounces, complaints, manual blocks)
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_suppressions (
  id          uuid primary key default gen_random_uuid(),
  email       text not null,
  reason      text not null,
  detail      text,
  is_permanent boolean not null default true,
  expires_at  timestamptz,
  created_by  uuid references auth.users (id) on delete set null,
  created_at  timestamptz not null default now(),
  constraint newsletter_suppressions_email_key unique (email),
  constraint newsletter_suppressions_reason_not_blank check (length(btrim(reason)) > 0)
);

create index if not exists newsletter_suppressions_expiry_idx
  on public.newsletter_suppressions (expires_at)
  where expires_at is not null;

-- ----------------------------------------------------------------------------
-- 15. Attributed revenue
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_conversions (
  id            uuid primary key default gen_random_uuid(),
  campaign_id   uuid references public.newsletter_campaigns (id) on delete set null,
  subscriber_id uuid references public.newsletter_subscribers (id) on delete set null,
  recipient_id  uuid references public.newsletter_campaign_recipients (id) on delete set null,
  external_id   text,
  amount_cents  bigint not null,
  currency      text not null default 'BRL',
  description   text,
  occurred_at   timestamptz not null default now(),
  metadata      jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  constraint newsletter_conversions_amount_positive check (amount_cents >= 0)
);

create unique index if not exists newsletter_conversions_external_key
  on public.newsletter_conversions (external_id)
  where external_id is not null;

create index if not exists newsletter_conversions_campaign_idx
  on public.newsletter_conversions (campaign_id, occurred_at desc);

create index if not exists newsletter_conversions_subscriber_idx
  on public.newsletter_conversions (subscriber_id, occurred_at desc);

-- ----------------------------------------------------------------------------
-- 16. Global sending settings (singleton row)
-- ----------------------------------------------------------------------------

create table if not exists public.newsletter_settings (
  id                    integer primary key default 1,
  default_from_name     text not null default 'Veritas & Lex',
  default_from_email    text not null default 'informativo@veritaslex.adv.br',
  default_reply_to      text,
  default_list_id       uuid references public.newsletter_lists (id) on delete set null,
  double_opt_in_enabled boolean not null default true,
  unsubscribe_footer    text,
  physical_address      text,
  privacy_policy_url    text,
  gdpr_contact_email    text,
  retry_max_attempts    integer not null default 3,
  retry_backoff_seconds integer not null default 60,
  throttle_per_second   integer not null default 10,
  daily_send_limit      integer,
  quiet_hours_start     time,
  quiet_hours_end       time,
  allowed_weekdays      smallint[] not null default '{1,2,3,4,5}',
  tracking_opens        boolean not null default true,
  tracking_clicks       boolean not null default true,
  utm_source            text not null default 'newsletter',
  utm_medium            text not null default 'email',
  utm_campaign_prefix   text not null default 'nl',
  updated_by            uuid references auth.users (id) on delete set null,
  updated_at            timestamptz not null default now(),
  constraint newsletter_settings_single_row check (id = 1),
  constraint newsletter_settings_throttle_positive
    check (retry_max_attempts > 0 and retry_backoff_seconds >= 0 and throttle_per_second > 0),
  constraint newsletter_settings_daily_limit_positive
    check (daily_send_limit is null or daily_send_limit > 0)
);

drop trigger if exists newsletter_settings_set_updated_at on public.newsletter_settings;
create trigger newsletter_settings_set_updated_at
  before update on public.newsletter_settings
  for each row execute function public.set_updated_at();

insert into public.newsletter_settings (id)
values (1)
on conflict (id) do nothing;

-- ----------------------------------------------------------------------------
-- 17. Row Level Security is enabled immediately; policies land in the next
--     migration together with the admin role helpers.
-- ----------------------------------------------------------------------------

alter table public.newsletter_lists               enable row level security;
alter table public.newsletter_tags                enable row level security;
alter table public.newsletter_subscribers         enable row level security;
alter table public.newsletter_list_members        enable row level security;
alter table public.newsletter_subscriber_tags     enable row level security;
alter table public.newsletter_segments            enable row level security;
alter table public.newsletter_templates           enable row level security;
alter table public.newsletter_campaigns           enable row level security;
alter table public.newsletter_campaign_versions   enable row level security;
alter table public.newsletter_providers           enable row level security;
alter table public.newsletter_campaign_recipients enable row level security;
alter table public.newsletter_links               enable row level security;
alter table public.newsletter_events              enable row level security;
alter table public.newsletter_suppressions        enable row level security;
alter table public.newsletter_conversions         enable row level security;
alter table public.newsletter_settings            enable row level security;
